### ISSUE TITLE
Server selector

### ISSUE THREAD

**Issue by yli-hallila** [yli-hallila/qupath-edu-webviewer#3]
Currently all API endpoints are hardcoded to `http://localhost` (https://github.com/yli-hallila/qupath-edu-webviewer/blob/master/src/components/OrganizationSelector.jsx#L8).

**To implement**
- [x] Allow users to define host for API endpoints when opening app for the first time (see Figure 1.)
- [x] Allow overriding host with a query parameter `?host=http://localhost` or similar
- [x] Show list of available public servers (available at https://edu.qupath.yli-hallila.fi/api/servers.json; see Figure 2.).
- [x] Save host to cookie / local storage
- [x] Allow resetting / changing host easily (in Java opens the Figure 1. dialog)
- [x] Validate host: check that the host is valid (any endpoint returning 200 OK is enough), if not: retry or change host (see Figure 3).

See [this](https://github.com/yli-hallila/qupath-edu-extension/blob/master/src/main/java/qupath/edu/gui/dialogs/FirstTimeSetup.java#L61) for Java implemenatation.

**Figures**

![java_4BqNZEgNkF](https://user-images.githubusercontent.com/45145923/136336807-aa9921e9-1941-4ec3-be16-b4138b130d6f.png)
**Figure 1**

![java_ekVq61Jhka](https://user-images.githubusercontent.com/45145923/136336899-92307bff-fb7b-40ca-ac17-98609f6c2102.png)
**Figure 2**

![java_wX4Ir2aaUI](https://user-images.githubusercontent.com/45145923/136336758-ef33a1ff-13e4-407e-8baf-56f5b0a1f7db.png)
**Figure 3**

**Comment by Luukuton** [comment]
Added a list of public servers with https://github.com/yli-hallila/qupath-edu-webviewer/commit/60f996b3a290f5575db296692c08124a2a32ccda

**Comment by Luukuton** [comment]
https://github.com/yli-hallila/qupath-edu-webviewer/pull/7 allows users to define private hosts and to save current host to browser's localStorage.

**Comment by Luukuton** [comment]
https://github.com/yli-hallila/qupath-edu-webviewer/pull/8 adds _overriding host with a query parameter_.

**Comment by Luukuton** [comment]
#8 also adds _Validate host_.
